const CONSTANTES = {
    LOGIN : 'LOGIN',
    POR_IMPLE : '*',
    ESTABLECER_SESION : 'ESTABLECER_SESION',
    SESSION_INVALID : 'SESSION_INVALID',
    GET_SESSION : 'GET_SESSION'
};

export default CONSTANTES;